# Input directory

input: # must contain .fa files
    "/hps/nobackup2/production/metagenomics/aalmeida/project_latinbiota/metaspades"

# output directory

output: # directory to store results (one folder per input file)
    "/hps/nobackup2/production/metagenomics/aalmeida/project_latinbiota/virsearch_wf"

# tools

usearch_binary:
    "tools/usearch"

# database folder

database: # must contain virsorter2, checkv, vibrant and dvf database files
    "/hps/nobackup2/production/metagenomics/aalmeida/databases/virsearch_db" 
