# Snakemake configuration

input:
    "test/input" # path to input directory with .fa files

output: 
    "test/output" # path to output directory

usearch_binary:
    "tools/usearch" # path to usearch binary

database: 
    "virsearch_db" # path to database folder
